tests: improve tests stack (#731)
* chore: fix missing npmScope

* test: scaffold shared-util-tests lib

* chore: fix type conflict version

* chore: add eslint import rules

* chore: fix babel-jest deps conflict

* chore: remove customQueries for now due to bug

```
  ● Test suite failed to run

    TypeError: fn.bind is not a function

      14 | console.log(document.body)
      15 | console.error(customQueries)
    > 16 | const customScreen = within(document.body, allQueries)
         |                            ^
      17 | const customWithin = (element: Parameters<typeof within>[0]) => within(element, allQueries)
      18 | function customRender(
      19 |   ...arg: Parameters<typeof render>

      at ../../../node_modules/@testing-library/dom/dist/get-queries-for-element.js:22:23
          at Array.reduce (<anonymous>)
      at getQueriesForElement (../../../node_modules/@testing-library/dom/dist/get-queries-for-element.js:20:31)
      at Object.<anonymous> (../../shared/util-tests/src/lib/shared-util-tests.tsx:16:28)
      at Object.require (../../shared/util-tests/src/index.ts:1:1)
      at Object.require (src/lib/feature/page-settings-resources-feature/page-settings-resources-feature.spec.tsx:12:1)

```

* chore: expose setupStore utility function

* chore: add external polyfills for tests

* chore: improve shared-util-tests to handle providers

* test: fix page-settings-resources-feature test

* chore: fix jest-dom import

* chore: deprecated __tests__ imports